# Generated by Django 5.1.2 on 2024-11-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BayerMain', '0006_alter_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='sumtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
