# Generated by Django 5.1.2 on 2024-11-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BayerMain', '0010_alter_feedback_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('kaspi', 'Клиент'), ('card', 'Картой при получений'), ('cash', 'Наличными при получений')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Open', max_length=50),
        ),
    ]
