# Generated by Django 5.1.2 on 2024-12-01 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BayerMain', '0016_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='static/sales')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BayerMain.product')),
            ],
        ),
    ]
