# Generated by Django 5.1.2 on 2024-12-01 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BayerMain', '0017_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='product',
        ),
        migrations.AddField(
            model_name='sales',
            name='name',
            field=models.CharField(default='Sale', max_length=255),
        ),
        migrations.CreateModel(
            name='productSales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productSales', to='BayerMain.product')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='BayerMain.sales')),
            ],
        ),
    ]
