# Generated by Django 5.1.2 on 2024-12-03 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BayerMain', '0019_imageuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageuser',
            name='image',
            field=models.ImageField(blank=True, default='static/img-profile/deanwinchester.jpg', null=True, upload_to='static/logoUser'),
        ),
        migrations.AlterField(
            model_name='imageuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to=settings.AUTH_USER_MODEL),
        ),
    ]
