# Generated by Django 5.1.2 on 2024-12-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BayerMain', '0022_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(blank=True, default='none', max_length=150, null=True),
        ),
    ]
